CREATE TABLE "users" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_name" VARCHAR(255) NOT NULL,
	"user_surname" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"is_verified" BOOLEAN NOT NULL,
	PRIMARY KEY("user_id")
);


CREATE TABLE "roles" (
	"role_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"role_name" VARCHAR(63),
	"description" TEXT,
	PRIMARY KEY("role_id")
);


CREATE TABLE "user_roles" (
	"user_id" INTEGER NOT NULL,
	"role_id" INTEGER NOT NULL,
	"assigned_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("user_id", "role_id")
);


CREATE TABLE "restaurants" (
	"restaurant_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"address" TEXT NOT NULL,
	"phone_number" VARCHAR(31),
	PRIMARY KEY("restaurant_id")
);


CREATE TABLE "tables" (
	"table_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"restaurant_id" INTEGER NOT NULL,
	"table_number" VARCHAR(255),
	"seats_number" INTEGER NOT NULL,
	"type" VARCHAR(63),
	PRIMARY KEY("table_id")
);


CREATE TABLE "reservations" (
	"reservation_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"table_id" INTEGER NOT NULL,
	"reservation_time_from" TIMESTAMP NOT NULL,
	"reservation_time_to" TIMESTAMP NOT NULL,
	"status" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("reservation_id")
);


ALTER TABLE "User"
ADD FOREIGN KEY("user_id") REFERENCES "user_roles"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_roles"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("role_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reservations"
ADD FOREIGN KEY("user_id") REFERENCES "User"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tables"
ADD FOREIGN KEY("table_id") REFERENCES "reservations"("table_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "restaurants"
ADD FOREIGN KEY("restaurant_id") REFERENCES "tables"("restaurant_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;